#!/usr/bin/env python3
"""Common period-4 Freudenthal torus, its barycentric subdivision, and the
four dual-block Heegaard handlebodies used by Lemma P0a.

Model
-----
``T`` is the Freudenthal/Kuhn triangulation of ``T^3 = R^3/(4 Z)^3``: for every
integer origin ``o`` in ``(Z/4)^3`` and every permutation ``(a,b,c)`` of the
three coordinate axes the four points

    o,  o+e_a,  o+e_a+e_b,  o+e_a+e_b+e_c = o+(1,1,1)

span a tetrahedron.  This is exactly the cover used by
``scripts/build_t73_ar_torus.py`` (64 cubes times 6 tetrahedra = 384
tetrahedra); that script reduces vertices by ``v -> (v+2) mod 4`` while this
module reduces by ``v -> v mod 4``.  The two conventions differ by the
translation ``v -> v+(2,2,2)``, a simplicial automorphism of the same mesh, so
the tetrahedron set is identical (``--check`` re-derives it and compares).

``T'`` is the first barycentric subdivision of ``T``: its vertices are the
barycentres of the simplices of ``T`` (64 + 448 + 768 + 384 = 1664 of them) and
its tetrahedra are the maximal chains ``v < e < f < t`` (384 * 24 = 9216).

Spines
------
For a base point ``b`` the *coordinate spine* ``K(b)`` is the union of the three
axis-parallel circles through ``b``; in the period-4 model it is a subcomplex of
``T`` with 10 vertices and 12 edges, so ``rank = E - V + 1 = 3``.

    Johnson pair   K_J^0  = K(0,0,0)      K_J^1  = K(2,2,2)
    AR pair        K_AR^0 = K(3,3,3)      K_AR^1 = K(1,1,1)

``(3,3,3) = (-1,-1,-1) mod 4`` is the AR base point ``Q`` and ``(1,1,1)`` is
``Qbar``.  The integer model of Johnson's affine map ``S(u)=2u-(1/2,1/2,1/2)``
is the translation ``T(v)=v-(1,1,1) mod 4`` of the *same* period-4 mesh.

Dual-block regular neighbourhoods
---------------------------------
For a subcomplex ``K`` of ``T`` the simplicial neighbourhood in ``T'`` is

    N(K;T')  =  union of the closed simplices of T' that meet |K|
             =  union over sigma in K of the dual block D(sigma),

where ``D(sigma)`` is the closure of the set of chains whose *minimal* element
is ``sigma``.  A chain ``c = (sigma_0 < ... < sigma_k)`` meets ``|K|`` iff some
vertex of ``sigma_0`` is a vertex of ``K``; in particular a *tetrahedron*
``(v<e<f<t)`` of ``T'`` lies in ``N(K;T')`` iff its minimal element ``v`` is a
vertex of ``K``.  ``N(K;T')`` is therefore the subcomplex of ``T'`` generated by
those tetrahedra.  This is the definition implemented below; no barycentre
distance comparison is used anywhere.

    H^0 := N(K^0; T')
    H^1 := closure of |T'| - |H^0|, i.e. the subcomplex of T' generated by the
           T'-tetrahedra whose minimal element is NOT a vertex of K^0.

(The frequently quoted identity ``closure of the complement = union of D(sigma)
over sigma not in K`` needs ``K`` full in ``T``.  The coordinate spines are
*not* full in this mesh -- e.g. the T-edge ``{(3,0,0),(0,1,0)}`` has both
endpoints on ``K_J^0`` but is not a spine edge -- so the closure-of-complement
definition above is used, and the fullness computation is reported honestly in
``geometry/t73_*_spines.json``.  Fullness of ``K`` in ``T`` is not needed: the
Rourke--Sanderson regular-neighbourhood theorem is applied to ``K'``, which is
always full in ``T'``, and in any case the certificate that is actually used is
the explicit elementary collapse ``H^i -> K^i`` produced by
``scripts/verify_elementary_collapse.py``.)

Outputs
-------
    geometry/t73_common_torus_triangulation.json
    geometry/t73_johnson_spines.json
    geometry/t73_ar_spines.json
    geometry/t73_handlebody_pair_dual_block.json
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from collections import Counter, defaultdict
from fractions import Fraction
from pathlib import Path
from typing import Any, Iterable, Sequence


ROOT = Path(__file__).resolve().parents[1]
GEOMETRY = ROOT / "geometry"
TRIANGULATION_OUTPUT = GEOMETRY / "t73_common_torus_triangulation.json"
JOHNSON_SPINE_OUTPUT = GEOMETRY / "t73_johnson_spines.json"
AR_SPINE_OUTPUT = GEOMETRY / "t73_ar_spines.json"
HANDLEBODY_OUTPUT = GEOMETRY / "t73_handlebody_pair_dual_block.json"

PERIOD = 4
AXES = ((1, 0, 0), (0, 1, 0), (0, 0, 1))

JOHNSON_BASES = {"K_J0": (0, 0, 0), "K_J1": (2, 2, 2)}
AR_BASES = {"K_AR0": (3, 3, 3), "K_AR1": (1, 1, 1)}
TRANSLATION = (-1, -1, -1)  # T(v) = v - (1,1,1) mod 4

Simplex = tuple[int, ...]


# --------------------------------------------------------------------------
# small helpers
# --------------------------------------------------------------------------


def canonical_sha(value: Any) -> str:
    raw = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(raw).hexdigest().upper()


def normalise(document: Any) -> Any:
    """Round-trip through JSON so tuples become lists before hashing/comparing."""
    return json.loads(json.dumps(document, sort_keys=True, separators=(",", ":")))


def vid(point: Sequence[int]) -> int:
    """Index of an integer point of Z^3 reduced modulo the period."""
    x, y, z = (int(c) % PERIOD for c in point)
    return (x * PERIOD + y) * PERIOD + z


def vcoords(index: int) -> tuple[int, int, int]:
    return (index // (PERIOD * PERIOD), (index // PERIOD) % PERIOD, index % PERIOD)


def faces_of(simplex: Simplex, size: int) -> Iterable[Simplex]:
    return itertools.combinations(simplex, size)


def closure(maximal: Iterable[Simplex]) -> set[Simplex]:
    """Every non-empty face of every listed simplex."""
    out: set[Simplex] = set()
    for cell in maximal:
        for size in range(1, len(cell) + 1):
            out.update(itertools.combinations(cell, size))
    return out


def facet_counts(simplices: Iterable[Simplex]) -> dict[Simplex, int]:
    """For each simplex, how many codimension-one cofaces are present."""
    present = set(simplices)
    counts: dict[Simplex, int] = defaultdict(int)
    for cell in present:
        if len(cell) == 1:
            continue
        for facet in itertools.combinations(cell, len(cell) - 1):
            counts[facet] += 1
    return counts


def euler_characteristic(simplices: Iterable[Simplex]) -> int:
    chi = 0
    for cell in simplices:
        chi += (-1) ** (len(cell) - 1)
    return chi


def dimension_counts(simplices: Iterable[Simplex]) -> dict[str, int]:
    counter = Counter(len(cell) - 1 for cell in simplices)
    return {f"dim{d}": counter.get(d, 0) for d in range(4)}


def link_is_sphere(star_top: list[Simplex], apex: int) -> bool:
    """Link of ``apex`` inside the pure 3-complex spanned by ``star_top``.

    Returns True when the link is a connected closed surface with chi = 2.
    """
    triangles = [tuple(v for v in cell if v != apex) for cell in star_top]
    edges: Counter[Simplex] = Counter()
    vertices: set[int] = set()
    for tri in triangles:
        vertices.update(tri)
        for edge in itertools.combinations(tri, 2):
            edges[edge] += 1
    if set(edges.values()) != {2}:
        return False
    if len(vertices) - len(edges) + len(triangles) != 2:
        return False
    adjacency: dict[int, set[int]] = defaultdict(set)
    for a, b in edges:
        adjacency[a].add(b)
        adjacency[b].add(a)
    start = next(iter(vertices))
    seen = {start}
    stack = [start]
    while stack:
        current = stack.pop()
        for other in adjacency[current]:
            if other not in seen:
                seen.add(other)
                stack.append(other)
    return seen == vertices


def surface_is_closed_connected(triangles: Sequence[Simplex]) -> tuple[bool, int, int]:
    """(closed and connected, chi, number of components) of a triangle list."""
    edges: Counter[Simplex] = Counter()
    vertices: set[int] = set()
    for tri in triangles:
        vertices.update(tri)
        for edge in itertools.combinations(tri, 2):
            edges[edge] += 1
    closed = set(edges.values()) == {2}
    chi = len(vertices) - len(edges) + len(triangles)
    adjacency: dict[int, set[int]] = defaultdict(set)
    for a, b in edges:
        adjacency[a].add(b)
        adjacency[b].add(a)
    unseen = set(vertices)
    components = 0
    while unseen:
        start = unseen.pop()
        components += 1
        stack = [start]
        while stack:
            current = stack.pop()
            for other in adjacency[current]:
                if other in unseen:
                    unseen.discard(other)
                    stack.append(other)
    return closed and components == 1, chi, components


# --------------------------------------------------------------------------
# the base triangulation T and its barycentric subdivision T'
# --------------------------------------------------------------------------


def build_base_triangulation() -> dict[str, Any]:
    lift_of: dict[Simplex, tuple[tuple[int, int, int], ...]] = {}
    tetrahedra: set[Simplex] = set()
    cover: list[tuple[Simplex, tuple[tuple[int, int, int], ...]]] = []
    lift_conflicts: list[Simplex] = []

    for origin in itertools.product(range(PERIOD), repeat=3):
        for permutation in itertools.permutations(range(3)):
            points = [tuple(origin)]
            for axis in permutation:
                previous = points[-1]
                points.append(tuple(previous[j] + AXES[axis][j] for j in range(3)))
            indices = [vid(point) for point in points]
            if len(set(indices)) != 4:
                raise AssertionError("Freudenthal tetrahedron degenerates modulo the period")
            key_tet = tuple(sorted(indices))
            tetrahedra.add(key_tet)
            ordered = tuple(point for _, point in sorted(zip(indices, points)))
            cover.append((key_tet, ordered))
            for size in range(1, 5):
                for positions in itertools.combinations(range(4), size):
                    pairs = sorted((indices[j], points[j]) for j in positions)
                    key = tuple(index for index, _ in pairs)
                    lift = tuple(point for _, point in pairs)
                    stored = lift_of.setdefault(key, lift)
                    if stored is not lift and barycentre(stored) != barycentre(lift):
                        lift_conflicts.append(key)

    if len(tetrahedra) != PERIOD**3 * 6:
        raise AssertionError(f"expected 384 tetrahedra, found {len(tetrahedra)}")
    if lift_conflicts:
        raise AssertionError(f"{len(lift_conflicts)} simplices have inconsistent lifts")

    by_dimension: dict[int, list[Simplex]] = {d: [] for d in range(4)}
    for key in lift_of:
        by_dimension[len(key) - 1].append(key)
    for value in by_dimension.values():
        value.sort()

    return {
        "lift_of": lift_of,
        "cover": cover,
        "simplices_by_dimension": by_dimension,
        "tetrahedra": sorted(tetrahedra),
    }


def barycentre(points: Sequence[Sequence[int]]) -> tuple[Fraction, Fraction, Fraction]:
    count = len(points)
    return tuple(  # type: ignore[return-value]
        (Fraction(sum(point[j] for point in points), count)) % PERIOD for j in range(3)
    )


def build_model() -> dict[str, Any]:
    base = build_base_triangulation()
    lift_of = base["lift_of"]
    by_dimension = base["simplices_by_dimension"]

    ordered_simplices: list[Simplex] = []
    for dimension in range(4):
        ordered_simplices.extend(by_dimension[dimension])
    tp_vertex_index = {simplex: position for position, simplex in enumerate(ordered_simplices)}
    for index in range(PERIOD**3):
        if tp_vertex_index[(index,)] != index:
            raise AssertionError("T-vertices must index the first block of T'-vertices")

    tprime_tets: list[Simplex] = []
    for tet in by_dimension[3]:
        for v in tet:
            for w in tet:
                if w == v:
                    continue
                edge = tuple(sorted((v, w)))
                for u in tet:
                    if u == v or u == w:
                        continue
                    triangle = tuple(sorted((v, w, u)))
                    chain = (
                        tp_vertex_index[(v,)],
                        tp_vertex_index[edge],
                        tp_vertex_index[triangle],
                        tp_vertex_index[tet],
                    )
                    if not (chain[0] < chain[1] < chain[2] < chain[3]):
                        raise AssertionError("chain indices are not increasing")
                    tprime_tets.append(chain)
    tprime_tets.sort()
    if len(tprime_tets) != len(by_dimension[3]) * 24:
        raise AssertionError("unexpected number of T'-tetrahedra")
    if len(set(tprime_tets)) != len(tprime_tets):
        raise AssertionError("T' has repeated tetrahedra")

    tprime_simplices = sorted(closure(tprime_tets), key=lambda s: (len(s), s))
    tprime_index = {simplex: position for position, simplex in enumerate(tprime_simplices)}

    barycentres = [barycentre(lift_of[simplex]) for simplex in ordered_simplices]

    model: dict[str, Any] = {
        "period": PERIOD,
        "lift_of": lift_of,
        "T_simplices_by_dimension": by_dimension,
        "T_tetrahedra": by_dimension[3],
        "Tprime_vertex_simplex": ordered_simplices,
        "Tprime_vertex_index": tp_vertex_index,
        "Tprime_vertex_barycentre": barycentres,
        "Tprime_tetrahedra": tprime_tets,
        "Tprime_simplices": tprime_simplices,
        "Tprime_simplex_index": tprime_index,
    }
    model["checks"] = check_triangulations(model)
    model["spines"] = {
        name: build_spine(model, base_point)
        for name, base_point in {**JOHNSON_BASES, **AR_BASES}.items()
    }
    model["handlebodies"] = build_handlebodies(model)
    model["pair_checks"] = {
        "johnson": check_pair(model, model["handlebodies"]["H_J0"], model["handlebodies"]["H_J1"]),
        "ar": check_pair(model, model["handlebodies"]["H_AR0"], model["handlebodies"]["H_AR1"]),
    }
    model["translation"] = check_translation(model, TRANSLATION)
    return model


def check_triangulations(model: dict[str, Any]) -> dict[str, Any]:
    by_dimension = model["T_simplices_by_dimension"]
    tets = by_dimension[3]

    triangle_multiplicity = Counter()
    for tet in tets:
        for triangle in itertools.combinations(tet, 3):
            triangle_multiplicity[triangle] += 1
    t_face_ok = set(triangle_multiplicity.values()) == {2}
    t_chi = (
        len(by_dimension[0]) - len(by_dimension[1]) + len(by_dimension[2]) - len(by_dimension[3])
    )

    star: dict[int, list[Simplex]] = defaultdict(list)
    for tet in tets:
        for vertex in tet:
            star[vertex].append(tet)
    t_links_ok = all(link_is_sphere(cells, vertex) for vertex, cells in star.items())

    tprime_tets = model["Tprime_tetrahedra"]
    tprime_triangle_multiplicity = Counter()
    for tet in tprime_tets:
        for triangle in itertools.combinations(tet, 3):
            tprime_triangle_multiplicity[triangle] += 1
    tp_face_ok = set(tprime_triangle_multiplicity.values()) == {2}
    tp_counts = dimension_counts(model["Tprime_simplices"])
    tp_chi = euler_characteristic(model["Tprime_simplices"])

    tp_star: dict[int, list[Simplex]] = defaultdict(list)
    for tet in tprime_tets:
        for vertex in tet:
            tp_star[vertex].append(tet)
    tp_links_ok = all(link_is_sphere(cells, vertex) for vertex, cells in tp_star.items())

    return {
        "T_vertices": len(by_dimension[0]),
        "T_edges": len(by_dimension[1]),
        "T_triangles": len(by_dimension[2]),
        "T_tetrahedra": len(by_dimension[3]),
        "T_euler_characteristic": t_chi,
        "T_every_triangle_in_two_tetrahedra": t_face_ok,
        "T_all_vertex_links_are_spheres": t_links_ok,
        "Tprime_vertices": tp_counts["dim0"],
        "Tprime_edges": tp_counts["dim1"],
        "Tprime_triangles": tp_counts["dim2"],
        "Tprime_tetrahedra": tp_counts["dim3"],
        "Tprime_euler_characteristic": tp_chi,
        "Tprime_every_triangle_in_two_tetrahedra": tp_face_ok,
        "Tprime_all_vertex_links_are_spheres": tp_links_ok,
    }


# --------------------------------------------------------------------------
# spines
# --------------------------------------------------------------------------


def spine_vertices_and_edges(base_point: Sequence[int]) -> tuple[set[int], set[Simplex]]:
    vertices: set[int] = set()
    edges: set[Simplex] = set()
    for axis in range(3):
        for step in range(PERIOD):
            head = list(base_point)
            head[axis] = base_point[axis] + step
            tail = list(base_point)
            tail[axis] = base_point[axis] + step + 1
            vertices.add(vid(head))
            vertices.add(vid(tail))
            edge = tuple(sorted((vid(head), vid(tail))))
            if len(set(edge)) != 2:
                raise AssertionError("degenerate spine edge")
            edges.add(edge)
    return vertices, edges


def build_spine(model: dict[str, Any], base_point: Sequence[int]) -> dict[str, Any]:
    vertices, edges = spine_vertices_and_edges(base_point)
    if len(vertices) != 10 or len(edges) != 12:
        raise AssertionError(f"spine at {tuple(base_point)} is not 10 vertices / 12 edges")

    t_edges = set(model["T_simplices_by_dimension"][1])
    if not edges <= t_edges:
        raise AssertionError("a spine edge is not an edge of T")

    adjacency: dict[int, set[int]] = defaultdict(set)
    for a, b in edges:
        adjacency[a].add(b)
        adjacency[b].add(a)
    unseen = set(vertices)
    components = 0
    while unseen:
        start = unseen.pop()
        components += 1
        stack = [start]
        while stack:
            current = stack.pop()
            for other in adjacency[current]:
                if other in unseen:
                    unseen.discard(other)
                    stack.append(other)
    rank = len(edges) - len(vertices) + components

    spine_simplices = {(v,) for v in vertices} | set(edges)
    non_full_witnesses: list[list[int]] = []
    for dimension in (1, 2, 3):
        for simplex in model["T_simplices_by_dimension"][dimension]:
            if set(simplex) <= vertices and simplex not in spine_simplices:
                non_full_witnesses.append(list(simplex))

    tp_index = model["Tprime_vertex_index"]
    kprime_vertices = sorted({tp_index[(v,)] for v in vertices} | {tp_index[e] for e in edges})
    kprime_edges = sorted(
        tuple(sorted((tp_index[(v,)], tp_index[edge])))
        for edge in edges
        for v in edge
    )
    if len(kprime_edges) != 24 or len(set(kprime_edges)) != 24:
        raise AssertionError("subdivided spine does not have 24 edges")
    kprime_simplices = {(v,) for v in kprime_vertices} | set(kprime_edges)

    kprime_vertex_set = set(kprime_vertices)
    kprime_full_in_tprime = True
    for simplex in model["Tprime_simplices"]:
        if set(simplex) <= kprime_vertex_set and simplex not in kprime_simplices:
            kprime_full_in_tprime = False
            break

    return {
        "base_point": [int(c) % PERIOD for c in base_point],
        "vertices": sorted(vertices),
        "vertex_coordinates": [list(vcoords(v)) for v in sorted(vertices)],
        "edges": sorted(edges),
        "components": components,
        "rank": rank,
        "full_subcomplex_of_T": not non_full_witnesses,
        "non_full_witnesses_in_T": sorted(non_full_witnesses),
        "subdivided_vertices": kprime_vertices,
        "subdivided_edges": kprime_edges,
        "subdivided_full_subcomplex_of_Tprime": kprime_full_in_tprime,
        "kprime_simplices": kprime_simplices,
    }


# --------------------------------------------------------------------------
# dual-block handlebodies
# --------------------------------------------------------------------------


def dual_block_neighbourhood(model: dict[str, Any], spine_vertices: set[int]) -> list[int]:
    """Indices (into Tprime_tetrahedra) of the T'-tetrahedra of N(K;T')."""
    return [
        position
        for position, chain in enumerate(model["Tprime_tetrahedra"])
        if chain[0] in spine_vertices
    ]


def handlebody_report(model: dict[str, Any], tet_positions: Sequence[int], spine_name: str) -> dict[str, Any]:
    tets = [model["Tprime_tetrahedra"][position] for position in tet_positions]
    simplices = closure(tets)
    counts = dimension_counts(simplices)
    chi = euler_characteristic(simplices)

    triangle_multiplicity: Counter[Simplex] = Counter()
    for tet in tets:
        for triangle in itertools.combinations(tet, 3):
            triangle_multiplicity[triangle] += 1
    multiplicity_profile = Counter(triangle_multiplicity.values())
    boundary = sorted(tri for tri, count in triangle_multiplicity.items() if count == 1)
    closed_connected, boundary_chi, boundary_components = surface_is_closed_connected(boundary)
    genus = (2 - boundary_chi) // 2 if boundary_chi % 2 == 0 else None

    spine = model["spines"][spine_name]
    contains_spine = spine["kprime_simplices"] <= simplices

    return {
        "spine": spine_name,
        "tetrahedron_indices": list(tet_positions),
        "tetrahedron_count": len(tets),
        "simplex_counts": counts,
        "euler_characteristic": chi,
        "triangle_multiplicity_profile": {str(k): v for k, v in sorted(multiplicity_profile.items())},
        "manifold_face_multiplicities": set(multiplicity_profile) <= {1, 2},
        "boundary_triangles": boundary,
        "boundary_triangle_count": len(boundary),
        "boundary_is_closed_connected_surface": closed_connected,
        "boundary_euler_characteristic": boundary_chi,
        "boundary_components": boundary_components,
        "boundary_genus": genus,
        "contains_subdivided_spine": contains_spine,
    }


def build_handlebodies(model: dict[str, Any]) -> dict[str, Any]:
    total = len(model["Tprime_tetrahedra"])
    out: dict[str, Any] = {}
    for zero_name, one_name in (("K_J0", "K_J1"), ("K_AR0", "K_AR1")):
        zero_vertices = set(model["spines"][zero_name]["vertices"])
        inside = dual_block_neighbourhood(model, zero_vertices)
        inside_set = set(inside)
        outside = [position for position in range(total) if position not in inside_set]
        out["H_" + zero_name[2:]] = handlebody_report(model, inside, zero_name)
        out["H_" + one_name[2:]] = handlebody_report(model, outside, one_name)
    return out


def check_pair(
    model: dict[str, Any],
    handle_zero: dict[str, Any],
    handle_one: dict[str, Any],
) -> dict[str, Any]:
    total = len(model["Tprime_tetrahedra"])
    zero = set(handle_zero["tetrahedron_indices"])
    one = set(handle_one["tetrahedron_indices"])
    disjoint = not (zero & one)
    fills = len(zero) + len(one) == total and zero | one == set(range(total))
    same_boundary = set(handle_zero["boundary_triangles"]) == set(handle_one["boundary_triangles"])
    genus_ok = handle_zero["boundary_genus"] == 3 and handle_one["boundary_genus"] == 3
    return {
        "tetrahedra_disjoint": disjoint,
        "union_is_Tprime": bool(disjoint and fills),
        "shared_boundary_triangles": same_boundary,
        "common_boundary_triangle_count": len(handle_zero["boundary_triangles"]),
        "common_boundary_genus": handle_zero["boundary_genus"],
        "both_boundaries_genus_three": genus_ok,
        "both_boundaries_closed_connected": bool(
            handle_zero["boundary_is_closed_connected_surface"]
            and handle_one["boundary_is_closed_connected_surface"]
        ),
    }


# --------------------------------------------------------------------------
# the translation S
# --------------------------------------------------------------------------


def translate_vertex(index: int, shift: Sequence[int]) -> int:
    coords = vcoords(index)
    return vid(tuple(coords[j] + shift[j] for j in range(3)))


def translate_simplex(simplex: Simplex, shift: Sequence[int]) -> Simplex:
    return tuple(sorted(translate_vertex(v, shift) for v in simplex))


def check_translation(model: dict[str, Any], shift: Sequence[int]) -> dict[str, Any]:
    tets = set(model["T_simplices_by_dimension"][3])
    simplicial = {translate_simplex(tet, shift) for tet in tets} == tets

    tp_index = model["Tprime_vertex_index"]

    def translate_tprime_vertex(index: int) -> int:
        return tp_index[translate_simplex(model["Tprime_vertex_simplex"][index], shift)]

    def translate_tprime_tet(chain: Simplex) -> Simplex:
        return tuple(sorted(translate_tprime_vertex(v) for v in chain))

    spine_images = {}
    for source, target in (("K_J0", "K_AR0"), ("K_J1", "K_AR1")):
        moved = {translate_vertex(v, shift) for v in model["spines"][source]["vertices"]}
        moved_edges = {
            translate_simplex(edge, shift) for edge in map(tuple, model["spines"][source]["edges"])
        }
        spine_images[source] = bool(
            moved == set(model["spines"][target]["vertices"])
            and moved_edges == {tuple(e) for e in model["spines"][target]["edges"]}
        )

    handlebody_images = {}
    if simplicial:
        tprime_tets = model["Tprime_tetrahedra"]
        for source, target in (("H_J0", "H_AR0"), ("H_J1", "H_AR1")):
            moved = {
                translate_tprime_tet(tprime_tets[position])
                for position in model["handlebodies"][source]["tetrahedron_indices"]
            }
            wanted = {
                tprime_tets[position]
                for position in model["handlebodies"][target]["tetrahedron_indices"]
            }
            handlebody_images[source] = moved == wanted
    else:
        handlebody_images = {"H_J0": False, "H_J1": False}

    return {
        "shift": [int(c) for c in shift],
        "formula_original": "S(u)=2u-(1/2,1/2,1/2)",
        "formula_scaled": "T(v)=v-(1,1,1) on the common period-4 Freudenthal mesh",
        "is_simplicial_automorphism_of_T": simplicial,
        "spine_images": spine_images,
        "handlebody_images": handlebody_images,
        "maps_handlebody_pair": bool(
            simplicial and all(spine_images.values()) and all(handlebody_images.values())
        ),
    }


def translation_maps_pair(model: dict[str, Any], shift: Sequence[int]) -> bool:
    """Mutation hook: does ``v -> v + shift`` carry the Johnson pair onto the AR pair?"""
    return bool(check_translation(model, shift)["maps_handlebody_pair"])


# --------------------------------------------------------------------------
# serialisation
# --------------------------------------------------------------------------


def frac(value: Fraction) -> str:
    return f"{value.numerator}/{value.denominator}"


def triangulation_document(model: dict[str, Any]) -> dict[str, Any]:
    by_dimension = model["T_simplices_by_dimension"]
    document = {
        "schema": "t73_common_torus_triangulation/v1",
        "generator": "scripts/build_t73_common_heegaard_complex.py",
        "period": PERIOD,
        "vertex_index_rule": "index = 16*x + 4*y + z for (x,y,z) in (Z/4)^3",
        "encoding": (
            "T-simplices are sorted tuples of T-vertex indices.  T'-vertices are "
            "indexed by the global order (dimension, sorted tuple) over the simplices "
            "of T, so T'-vertex i < 64 is the T-vertex i.  T'-tetrahedra are the "
            "maximal chains v<e<f<t written as increasing 4-tuples of T'-vertex indices."
        ),
        "T": {
            "vertices": [list(vcoords(v)) for v, in by_dimension[0]],
            "edges": [list(edge) for edge in by_dimension[1]],
            "triangles": [list(triangle) for triangle in by_dimension[2]],
            "tetrahedra": [list(tet) for tet in by_dimension[3]],
            "integer_lifts": {
                "note": "one lift per simplex, ordered like the sorted index tuple",
                "edges": [
                    [list(point) for point in model["lift_of"][edge]] for edge in by_dimension[1]
                ],
                "triangles": [
                    [list(point) for point in model["lift_of"][triangle]]
                    for triangle in by_dimension[2]
                ],
                "tetrahedra": [
                    [list(point) for point in model["lift_of"][tet]] for tet in by_dimension[3]
                ],
            },
        },
        "Tprime": {
            "vertex_simplex_of_T": [list(simplex) for simplex in model["Tprime_vertex_simplex"]],
            "vertex_barycentre_mod_period": [
                [frac(coord) for coord in point] for point in model["Tprime_vertex_barycentre"]
            ],
            "tetrahedra": [list(tet) for tet in model["Tprime_tetrahedra"]],
            "simplex_count": len(model["Tprime_simplices"]),
        },
        "checks": model["checks"],
    }
    document = normalise(document)
    document["document_sha256"] = canonical_sha(document)
    return document


def spine_document(model: dict[str, Any], names: Sequence[str], label: str) -> dict[str, Any]:
    document: dict[str, Any] = {
        "schema": "t73_spine_pair/v1",
        "generator": "scripts/build_t73_common_heegaard_complex.py",
        "model": label,
        "period": PERIOD,
        "triangulation": "geometry/t73_common_torus_triangulation.json",
        "rank_formula": "rank = E - V + components",
        "spines": {},
    }
    for name in names:
        spine = model["spines"][name]
        document["spines"][name] = {
            key: value for key, value in spine.items() if key != "kprime_simplices"
        }
        document["spines"][name]["edge_coordinates"] = [
            [list(vcoords(a)), list(vcoords(b))] for a, b in spine["edges"]
        ]
    document["all_ranks_are_three"] = all(
        model["spines"][name]["rank"] == 3 for name in names
    )
    document["all_subdivided_spines_full_in_Tprime"] = all(
        model["spines"][name]["subdivided_full_subcomplex_of_Tprime"] for name in names
    )
    document["fullness_note"] = (
        "full_subcomplex_of_T records the literal fullness test in T and is False: "
        "e.g. the T-edge joining two spine vertices on different axis circles is not "
        "a spine edge.  The regular-neighbourhood theorem is applied to the "
        "subdivided spine K', which is always full in T' "
        "(subdivided_full_subcomplex_of_Tprime), and the certificate actually used is "
        "the explicit elementary collapse produced by "
        "scripts/verify_elementary_collapse.py."
    )
    document = normalise(document)
    document["document_sha256"] = canonical_sha(document)
    return document


def handlebody_document(model: dict[str, Any]) -> dict[str, Any]:
    handlebodies = {}
    for name, report in model["handlebodies"].items():
        handlebodies[name] = {
            key: value
            for key, value in report.items()
            if key not in {"boundary_triangles"}
        }
        handlebodies[name]["boundary_triangles"] = [
            list(triangle) for triangle in report["boundary_triangles"]
        ]
    document = {
        "schema": "t73_handlebody_pair_dual_block/v1",
        "generator": "scripts/build_t73_common_heegaard_complex.py",
        "period": PERIOD,
        "triangulation": "geometry/t73_common_torus_triangulation.json",
        "definition": (
            "H^0 = N(K^0;T') = subcomplex of T' generated by the T'-tetrahedra whose "
            "minimal chain element is a vertex of K^0 (union of the dual blocks D(sigma), "
            "sigma in K^0).  H^1 = closure of the complement, i.e. the subcomplex "
            "generated by the remaining T'-tetrahedra.  No barycentre distance "
            "comparison is used."
        ),
        "handlebodies": handlebodies,
        "pair_checks": model["pair_checks"],
        "translation": model["translation"],
    }
    document = normalise(document)
    document["document_sha256"] = canonical_sha(document)
    return document


def documents(model: dict[str, Any]) -> dict[Path, dict[str, Any]]:
    return {
        TRIANGULATION_OUTPUT: triangulation_document(model),
        JOHNSON_SPINE_OUTPUT: spine_document(model, ("K_J0", "K_J1"), "johnson"),
        AR_SPINE_OUTPUT: spine_document(model, ("K_AR0", "K_AR1"), "ar"),
        HANDLEBODY_OUTPUT: handlebody_document(model),
    }


def dump(document: dict[str, Any]) -> str:
    return json.dumps(document, sort_keys=True, separators=(",", ":")) + "\n"


# --------------------------------------------------------------------------
# cross-check against the committed AR torus
# --------------------------------------------------------------------------


def committed_ar_tetrahedra() -> set[Simplex]:
    import importlib.util

    path = ROOT / "scripts" / "build_t73_ar_torus.py"
    spec = importlib.util.spec_from_file_location("build_t73_ar_torus", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    torus = module.generate()
    return {tuple(sorted(vid(vertex) for vertex in tet)) for tet in torus["cover_tetrahedra"]}


# --------------------------------------------------------------------------
# summary and CLI
# --------------------------------------------------------------------------


def summary(model: dict[str, Any]) -> dict[str, Any]:
    checks = model["checks"]
    ranks = {name: model["spines"][name]["rank"] for name in model["spines"]}
    return {
        "T_tetrahedra": checks["T_tetrahedra"],
        "Tprime_tetrahedra": checks["Tprime_tetrahedra"],
        "spine_ranks": ranks,
        "handlebody_tetrahedron_counts": {
            name: report["tetrahedron_count"] for name, report in model["handlebodies"].items()
        },
        "handlebody_euler_characteristics": {
            name: report["euler_characteristic"] for name, report in model["handlebodies"].items()
        },
        "boundary_genus": {
            name: report["boundary_genus"] for name, report in model["handlebodies"].items()
        },
        "pair_checks": model["pair_checks"],
        "translation_maps_pair": model["translation"]["maps_handlebody_pair"],
    }


def print_lines(model: dict[str, Any], ar_match: bool | None) -> bool:
    checks = model["checks"]
    ok = True
    ok &= checks["T_euler_characteristic"] == 0
    ok &= checks["T_every_triangle_in_two_tetrahedra"]
    ok &= checks["T_all_vertex_links_are_spheres"]
    ok &= checks["Tprime_euler_characteristic"] == 0
    ok &= checks["Tprime_every_triangle_in_two_tetrahedra"]
    ok &= checks["Tprime_all_vertex_links_are_spheres"]
    ranks = sorted({model["spines"][name]["rank"] for name in model["spines"]})
    ok &= ranks == [3]
    union_ok = all(
        model["pair_checks"][pair]["union_is_Tprime"]
        and model["pair_checks"][pair]["shared_boundary_triangles"]
        for pair in model["pair_checks"]
    )
    genus_ok = all(
        model["pair_checks"][pair]["both_boundaries_genus_three"]
        and model["pair_checks"][pair]["both_boundaries_closed_connected"]
        for pair in model["pair_checks"]
    )
    ok &= union_ok and genus_ok
    ok &= model["translation"]["maps_handlebody_pair"]
    if ar_match is not None:
        ok &= ar_match

    print(f"T_TETRAHEDRA={checks['T_tetrahedra']}")
    print(f"TPRIME_TETRAHEDRA={checks['Tprime_tetrahedra']}")
    print(f"TPRIME_CLOSED_MANIFOLD={'PASS' if checks['Tprime_every_triangle_in_two_tetrahedra'] and checks['Tprime_all_vertex_links_are_spheres'] and checks['Tprime_euler_characteristic'] == 0 else 'FAIL'}")
    print(f"SPINE_RANK={ranks[0] if len(ranks) == 1 else ranks}")
    for name in ("H_J0", "H_J1", "H_AR0", "H_AR1"):
        report = model["handlebodies"][name]
        print(
            f"{name}_TETS={report['tetrahedron_count']} CHI={report['euler_characteristic']} "
            f"BOUNDARY_GENUS={report['boundary_genus']}"
        )
    print(f"COMMON_BOUNDARY_GENUS={model['pair_checks']['johnson']['common_boundary_genus']}")
    print(f"UNION_IS_T3={'PASS' if union_ok else 'FAIL'}")
    print(
        "S_MAPS_HANDLEBODY_PAIR="
        f"{'PASS' if model['translation']['maps_handlebody_pair'] else 'FAIL'}"
    )
    if ar_match is not None:
        print(f"MATCHES_COMMITTED_AR_TORUS={'PASS' if ar_match else 'FAIL'}")
    print(f"DUAL_BLOCK_COMPLEX={'PASS' if ok else 'FAIL'}")
    return bool(ok)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write the geometry/*.json files")
    parser.add_argument("--check", action="store_true", help="recompute and compare with the committed files")
    parser.add_argument("--skip-ar-crosscheck", action="store_true")
    args = parser.parse_args()

    model = build_model()
    ar_match: bool | None = None
    if not args.skip_ar_crosscheck:
        ar_match = committed_ar_tetrahedra() == set(model["T_simplices_by_dimension"][3])

    produced = documents(model)
    if args.write:
        GEOMETRY.mkdir(parents=True, exist_ok=True)
        for path, document in produced.items():
            path.write_text(dump(document), encoding="utf-8")
            print(f"WROTE={path.relative_to(ROOT)} BYTES={path.stat().st_size}")

    ok = print_lines(model, ar_match)

    if args.check:
        mismatched = []
        for path, document in produced.items():
            if not path.exists():
                mismatched.append(f"{path.relative_to(ROOT)}:MISSING")
                continue
            committed = json.loads(path.read_text(encoding="utf-8"))
            if committed != document:
                mismatched.append(f"{path.relative_to(ROOT)}:DIFFERS")
        print(f"COMMITTED_GEOMETRY={'PASS' if not mismatched else 'FAIL ' + ','.join(mismatched)}")
        ok = ok and not mismatched

    if not args.write and not args.check:
        print(json.dumps(summary(model), indent=2, sort_keys=True))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
