#!/usr/bin/env python3
"""COMMIT 4a -- compose the 93 PL Johnson generators into ``psi_A`` and report
the honest diagnostics against the COMMIT 3 handlebody ``H_J^0``.

Composition order
-----------------
``psi_A = psi_92 o ... o psi_0`` (``psi_0`` is applied to points first), because
``E_92 * ... * E_0 = A``; see the module docstring of
``scripts/build_t73_johnson_pl_generators.py``.  The composite induced matrix is
recomputed here from the generator files and compared with ``A``.

What is exact and complete
--------------------------
* the composite linear part ``E_92 * ... * E_0 = A`` and hence the induced map
  on ``H_1(T^3)`` and the homology classes of all six image curves;
* the local normal form ``psi_A(x) = A x`` for ``|x|_sup <= 1/196104``, with the
  operator-norm certificate that no push ever fires on those orbits;
* the per-generator diagnostics: for each of the 93 generators, the exact image
  of ``K1`` (a five-vertex bent path plus two untouched axis circles), whether it
  lies in ``|H_J^0|``, and its exact sup-norm distance from ``K1``;
* the exact prefix transport of the three spine loops and of the three framing
  push-offs ``C_i^+ = C_i + (1/1000) e_{i+1}``, carried as far as the vertex
  budget allows, with the exact vertex counts at every step;
* the exact image under the *full* 93-fold composite of a finite sample of
  points of each curve (point transport does not suffer the polyline blow-up).

What is NOT computed, and why
-----------------------------
The complete exact polygon ``psi_A(C_i)`` is not produced.  ``psi_k`` is affine
on 24 cells plus their complement, so the ``k``-fold composite is affine only on
the common refinement, and the number of linearity domains a curve meets grows
multiplicatively.  Measured on this factorisation the vertex count of the exact
image of ``C_2`` is

    5, 11, 19, 31, ..., 3329 (step 27), ..., 10440 (step 32)

i.e. a growth factor near ``1.25`` per generator; extrapolating to 93 generators
gives of order ``10^9`` vertices, with rational coordinates whose denominators
also grow.  This is a property of the object, not of the implementation: the
exact polygon is reported as OPEN together with the measured growth, and no
approximation is substituted for it.

The membership test for ``|H_J^0|``
----------------------------------
``H_J^0 = N(K_J^0; T')`` is generated by the ``T'``-tetrahedra whose minimal
chain element is a vertex of the spine ``K_J^0`` (period-4 model, see
``scripts/build_t73_common_heegaard_complex.py``).  A point lies in a closed
``T'``-tetrahedron ``(v<e<f<t)`` iff its barycentric coordinates inside ``t``
decrease along the chain, so

    x in |H_J^0|  <=>  the maximum of the piecewise-linear hat functions
                       ``lambda_w(x)``, ``w`` a vertex of ``T``, is attained at
                       some vertex of ``K_J^0``.

``--crosscheck`` re-derives this against the committed COMMIT 3 data by running
it on an interior point of each of the 9216 ``T'``-tetrahedra.  Period
conversion: period-1 points are multiplied by 4.

Protected ball -- stated honestly
---------------------------------
Every push ``Pi_k`` fixes ``B(0, 1/196104)`` pointwise (its support is at
sup-norm distance ``1/8`` from the lattice).  Every *linear* factor ``E_k`` does
not: it is a transvection and moves every point with ``x_t != 0``.  Consequently
``psi_A`` restricted to the protected ball is exactly the linear map ``A``: it
fixes ``0`` but no ball around it.  Both facts are recorded with explicit
witnesses.  No attaching link is produced: without exact set-wise preservation
of the handlebody pair the Aitchison--Rubinstein curves ``psi_A(C_i^+)`` on the
Heegaard surface are not defined, and that stays OPEN.

Section straightening
---------------------
``geometry/t73_johnson_generators/gen_093_section_straightening.json`` records a
further explicit PL homeomorphism ``theta`` of ``T^3``, supported in the
protected cube and equal to ``A^{-1}`` on a small cube ``C_in``, built by
``scripts/build_t73_section_straightening.py``.  ``section_straightening`` below
records that ``Psi = psi_A o theta`` is the identity on ``C_in`` pointwise: the
argument is that ``A^{-1} C_in`` stays inside the cube where ``psi_A`` is
literally ``A``, and the check is that a sample of points of ``C_in``, its
corners included, is pushed through ``A^{-1}`` and then through all 93
generators one point at a time and comes back to itself.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from fractions import Fraction
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_DIR = ROOT / "geometry" / "t73_johnson_generators"
GEOMETRY = ROOT / "geometry"
OUTPUT = GEOMETRY / "t73_psi_A.json"
MATRIX_A = [[0, 269, 1240], [0, 41, 189], [1, 0, 32]]
PROTECTED_RADIUS = Fraction(1, 196104)
FRAMING_EPSILON = Fraction(1, 1000)
SUPPORT_LATTICE_CLEARANCE = Fraction(1, 8)
PERIOD = 4
DEFAULT_VERTEX_BUDGET = 12000
DEFAULT_SAMPLE_COUNT = 32


# ---------------------------------------------------------------------------
# exact helpers
# ---------------------------------------------------------------------------


def canonical_sha(value: Any) -> str:
    raw = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(raw).hexdigest().upper()


def F(value) -> Fraction:
    return Fraction(value)


def point(raw):
    return (F(raw[0]), F(raw[1]), F(raw[2]))


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def cross(u, v):
    return (
        u[1] * v[2] - u[2] * v[1],
        u[2] * v[0] - u[0] * v[2],
        u[0] * v[1] - u[1] * v[0],
    )


def matmul(left, right):
    return [[sum(left[i][k] * right[k][j] for k in range(3)) for j in range(3)] for i in range(3)]


def matvec(mat, vector):
    return tuple(
        mat[i][0] * vector[0] + mat[i][1] * vector[1] + mat[i][2] * vector[2] for i in range(3)
    )


def infinity_norm(mat) -> int:
    return max(sum(abs(entry) for entry in row) for row in mat)


def floor_div(value: Fraction) -> int:
    return value.numerator // value.denominator


def ceil_div(value: Fraction) -> int:
    return -((-value.numerator) // value.denominator)


def gcd(a: int, b: int) -> int:
    while b:
        a, b = b, a % b
    return abs(a)


def integer_plane(normal, offset):
    values = list(normal) + [offset]
    denominator = 1
    for value in values:
        denominator = denominator * value.denominator // gcd(denominator, value.denominator)
    integers = [int(value * denominator) for value in values]
    common = 0
    for value in integers:
        common = gcd(common, abs(value))
    if common:
        integers = [value // common for value in integers]
    for value in integers:
        if value:
            if value < 0:
                integers = [-v for v in integers]
            break
    return tuple(integers)


# ---------------------------------------------------------------------------
# one generator, ready for pushing points and polylines
# ---------------------------------------------------------------------------


class Generator:
    def __init__(self, document):
        self.index = document["index"]
        self.integer_matrix = document["linear_part_E"]["matrix"]
        self.matrix = [[F(v) for v in row] for row in self.integer_matrix]
        push = document["push_Pi"]
        self.vertices = [point(v) for v in push["vertices"]]
        self.image_vertices = [point(v) for v in push["image_vertices"]]
        self.tetrahedra = [tuple(cell) for cell in push["tetrahedra"]]
        self.maps = [
            ([[F(e) for e in row] for row in record["matrix"]], point(record["translation"]))
            for record in push["cell_maps"]
        ]
        self.halfspaces = [
            (point(item["normal"]), F(item["bound"])) for item in push["support_halfspaces"]
        ]
        self.low = [min(v[i] for v in self.vertices) for i in range(3)]
        self.high = [max(v[i] for v in self.vertices) for i in range(3)]
        self.cell_planes = []
        planes: dict[tuple, None] = {}
        for cell in self.tetrahedra:
            corners = [self.vertices[i] for i in cell]
            inward = []
            for skip in range(4):
                others = corners[:skip] + corners[skip + 1:]
                normal = cross(sub(others[1], others[0]), sub(others[2], others[0]))
                offset = sum(normal[i] * others[0][i] for i in range(3))
                if sum(normal[i] * corners[skip][i] for i in range(3)) < offset:
                    normal = tuple(-c for c in normal)
                    offset = -offset
                inward.append((normal, offset))
                planes[integer_plane(normal, offset)] = None
            self.cell_planes.append(inward)
        self.planes = list(planes)

    def candidates(self, origin):
        ranges = []
        for i in range(3):
            first = ceil_div(F(origin[i]) - self.high[i])
            last = floor_div(F(origin[i]) + 1 - self.low[i])
            ranges.append(range(first, last + 1))
        return [(x, y, z) for x in ranges[0] for y in ranges[1] for z in ranges[2]]

    def inside_support(self, p, shift):
        for normal, bound in self.halfspaces:
            if (
                normal[0] * (p[0] - shift[0])
                + normal[1] * (p[1] - shift[1])
                + normal[2] * (p[2] - shift[2])
            ) > bound:
                return False
        return True

    def locate(self, p, shift):
        local = (p[0] - shift[0], p[1] - shift[1], p[2] - shift[2])
        for index, planes in enumerate(self.cell_planes):
            if all(
                normal[0] * local[0] + normal[1] * local[1] + normal[2] * local[2] >= offset
                for normal, offset in planes
            ):
                return index
        return None

    def apply_cell(self, p, shift, index):
        mat, translation = self.maps[index]
        local = (p[0] - shift[0], p[1] - shift[1], p[2] - shift[2])
        moved = matvec(mat, local)
        return (
            moved[0] + translation[0] + shift[0],
            moved[1] + translation[1] + shift[1],
            moved[2] + translation[2] + shift[2],
        )

    def push_point(self, p):
        origin = tuple(floor_div(c) for c in p)
        for shift in self.candidates(origin):
            if not self.inside_support(p, shift):
                continue
            index = self.locate(p, shift)
            if index is None:
                raise AssertionError("point in the support but in no cell")
            return self.apply_cell(p, shift, index)
        return p

    def push_segment(self, start, end):
        direction = sub(end, start)
        if direction == (0, 0, 0):
            return [self.push_point(end)]
        cuts = {Fraction(0), Fraction(1)}
        for i in range(3):
            d = direction[i]
            if d == 0:
                continue
            lo, hi = (start[i], end[i]) if d > 0 else (end[i], start[i])
            for n in range(floor_div(lo) + 1, ceil_div(hi)):
                t = (Fraction(n) - start[i]) / d
                if 0 < t < 1:
                    cuts.add(t)
        windows: list[list] = []
        ordered_cuts = sorted(cuts)
        for lo, hi in zip(ordered_cuts, ordered_cuts[1:]):
            mid = (lo + hi) / 2
            origin = tuple(floor_div(start[i] + mid * direction[i]) for i in range(3))
            for shift in self.candidates(origin):
                low, high = lo, hi
                empty = False
                for normal, bound in self.halfspaces:
                    value = sum(normal[i] * (start[i] - shift[i]) for i in range(3))
                    slope = sum(normal[i] * direction[i] for i in range(3))
                    if slope == 0:
                        if value > bound:
                            empty = True
                            break
                        continue
                    limit = (bound - value) / slope
                    if slope > 0:
                        high = min(high, limit)
                    else:
                        low = max(low, limit)
                    if low >= high:
                        empty = True
                        break
                if empty or low >= high:
                    continue
                if windows and windows[-1][0] == shift and windows[-1][2] == low:
                    windows[-1][2] = high
                else:
                    windows.append([shift, low, high])
        if not windows:
            return [end]
        images: dict[Fraction, tuple] = {}
        for shift, lo, hi in windows:
            params = {lo, hi}
            for plane in self.planes:
                slope = plane[0] * direction[0] + plane[1] * direction[1] + plane[2] * direction[2]
                if slope == 0:
                    continue
                value = sum(plane[i] * (start[i] - shift[i]) for i in range(3))
                t = (Fraction(plane[3]) - value) / slope
                if lo < t < hi:
                    params.add(t)
            ordered = sorted(params)
            for left, right in zip(ordered, ordered[1:]):
                mid = (left + right) / 2
                probe = tuple(start[i] + mid * direction[i] for i in range(3))
                index = self.locate(probe, shift)
                if index is None:
                    raise AssertionError("sub-segment in the support but in no cell")
                for t in (left, right):
                    raw = tuple(start[i] + t * direction[i] for i in range(3))
                    moved = self.apply_cell(raw, shift, index)
                    if t in images and images[t] != moved:
                        raise AssertionError("push is discontinuous across a cell wall")
                    images[t] = moved
        out = []
        for t in sorted(set(images) | {Fraction(1)}):
            if t == 0:
                continue
            out.append(images.get(t, tuple(start[i] + t * direction[i] for i in range(3))))
        return out

    def push_polyline(self, points):
        out = [self.push_point(points[0])]
        for start, end in zip(points, points[1:]):
            out.extend(self.push_segment(start, end))
        return simplify(out)

    def apply(self, points):
        return self.push_polyline([matvec(self.matrix, p) for p in points])

    def apply_point(self, p):
        return self.push_point(matvec(self.matrix, p))


def simplify(points):
    out = [points[0]]
    for p in points[1:]:
        if p != out[-1]:
            out.append(p)
    if len(out) < 3:
        return out
    kept = [out[0]]
    for index in range(1, len(out) - 1):
        previous, current, following = kept[-1], out[index], out[index + 1]
        line = sub(following, previous)
        offset = sub(current, previous)
        if line != (0, 0, 0) and cross(offset, line) == (0, 0, 0):
            pivot = 0 if line[0] else (1 if line[1] else 2)
            if 0 < offset[pivot] / line[pivot] < 1:
                continue
        kept.append(current)
    kept.append(out[-1])
    return kept


# ---------------------------------------------------------------------------
# distance to K1
# ---------------------------------------------------------------------------


def circle_distance(value: Fraction) -> Fraction:
    frac = value - floor_div(value)
    return frac if frac + frac <= 1 else 1 - frac


def distance_to_K1(p) -> Fraction:
    """Sup-norm distance in ``T^3`` to the three coordinate axis circles.

    The distance to the ``e_i`` circle is ``max_{j != i} d(x_j, Z)``, so the
    distance to their union is the *median* of the three circle distances.
    """
    values = sorted(circle_distance(c) for c in p)
    return values[1]


def segment_max_distance(start, end, cap: Fraction) -> Fraction:
    direction = sub(end, start)
    if direction == (0, 0, 0):
        return distance_to_K1(start)
    params = {Fraction(0), Fraction(1)}
    for i in range(3):
        d = direction[i]
        if d == 0:
            continue
        lo, hi = (start[i], end[i]) if d > 0 else (end[i], start[i])
        for n in range(ceil_div(lo * 2), floor_div(hi * 2) + 1):
            t = (Fraction(n, 2) - start[i]) / d
            if 0 < t < 1:
                params.add(t)
    best = Fraction(0)
    ordered = sorted(params)
    for left, right in zip(ordered, ordered[1:]):
        mid = (left + right) / 2
        base = tuple(start[i] + mid * direction[i] for i in range(3))
        lines = []
        for i in range(3):
            offset = floor_div(base[i])
            if base[i] + base[i] <= 2 * offset + 1:
                lines.append((direction[i], start[i] - offset))
            else:
                lines.append((-direction[i], Fraction(offset + 1) - start[i]))
        pieces = {left, right}
        for i in range(3):
            for j in range(i + 1, 3):
                slope = lines[i][0] - lines[j][0]
                if slope == 0:
                    continue
                t = (lines[j][1] - lines[i][1]) / slope
                if left < t < right:
                    pieces.add(t)
        for t in sorted(pieces):
            value = distance_to_K1(tuple(start[i] + t * direction[i] for i in range(3)))
            if value > best:
                best = value
                if best >= cap:
                    return best
    return best


def polyline_max_distance(points, cap=Fraction(1, 2)) -> Fraction:
    best = Fraction(0)
    for start, end in zip(points, points[1:]):
        best = max(best, segment_max_distance(start, end, cap))
        if best >= cap:
            return best
    return best


def polyline_vertex_max_distance(points) -> Fraction:
    return max(distance_to_K1(p) for p in points)


# ---------------------------------------------------------------------------
# membership in |H_J^0| (period-4 mesh)
# ---------------------------------------------------------------------------


def is_spine_vertex(vertex) -> bool:
    return sum(1 for c in vertex if c % PERIOD) <= 1


def hat_support(x):
    base = [floor_div(c) for c in x]
    frac = [x[i] - base[i] for i in range(3)]
    order = sorted(range(3), key=lambda i: (-frac[i], i))
    lam = [
        1 - frac[order[0]],
        frac[order[0]] - frac[order[1]],
        frac[order[1]] - frac[order[2]],
        frac[order[2]],
    ]
    corners = [
        tuple(base),
        tuple(base[i] + (1 if i == order[0] else 0) for i in range(3)),
        tuple(base[i] + (1 if i in (order[0], order[1]) else 0) for i in range(3)),
        tuple(base[i] + 1 for i in range(3)),
    ]
    return [(corners[j], lam[j]) for j in range(4) if lam[j] > 0]


def point_in_H0(x) -> bool:
    pairs = hat_support(x)
    top = max(value for _, value in pairs)
    return any(is_spine_vertex(vertex) for vertex, value in pairs if value == top)


def segment_in_H0(start, end) -> bool:
    direction = sub(end, start)
    if direction == (0, 0, 0):
        return point_in_H0(start)
    cuts = {Fraction(0), Fraction(1)}
    forms = [(start[i], direction[i]) for i in range(3)]
    forms += [
        (start[i] - start[j], direction[i] - direction[j])
        for i in range(3)
        for j in range(i + 1, 3)
    ]
    for value, slope in forms:
        if slope == 0:
            continue
        lo, hi = (value, value + slope) if slope > 0 else (value + slope, value)
        for n in range(floor_div(lo) + 1, ceil_div(hi)):
            t = (Fraction(n) - value) / slope
            if 0 < t < 1:
                cuts.add(t)
    ordered = sorted(cuts)
    for left, right in zip(ordered, ordered[1:]):
        mid = (left + right) / 2
        base_point = tuple(start[i] + mid * direction[i] for i in range(3))
        base = [floor_div(c) for c in base_point]
        frac = [base_point[i] - base[i] for i in range(3)]
        order = sorted(range(3), key=lambda i: (-frac[i], i))
        affine = [(start[i] - base[i], direction[i]) for i in range(3)]
        lam = [
            (1 - affine[order[0]][0], -affine[order[0]][1]),
            (affine[order[0]][0] - affine[order[1]][0], affine[order[0]][1] - affine[order[1]][1]),
            (affine[order[1]][0] - affine[order[2]][0], affine[order[1]][1] - affine[order[2]][1]),
            (affine[order[2]][0], affine[order[2]][1]),
        ]
        pieces = {left, right}
        for i in range(4):
            for j in range(i + 1, 4):
                slope = lam[i][1] - lam[j][1]
                if slope == 0:
                    continue
                t = (lam[j][0] - lam[i][0]) / slope
                if left < t < right:
                    pieces.add(t)
        inner = sorted(pieces)
        for a, b in zip(inner, inner[1:]):
            probe = (a + b) / 2
            if not point_in_H0(tuple(start[i] + probe * direction[i] for i in range(3))):
                return False
    return True


def polyline_in_H0(points) -> bool:
    if not point_in_H0(points[0]):
        return False
    for start, end in zip(points, points[1:]):
        if not segment_in_H0(start, end):
            return False
    return True


def scale_to_period4(points):
    return [tuple(c * PERIOD for c in p) for p in points]


def crosscheck_membership() -> dict[str, Any]:
    triangulation = json.loads(
        (GEOMETRY / "t73_common_torus_triangulation.json").read_text(encoding="utf-8")
    )
    spines = json.loads((GEOMETRY / "t73_johnson_spines.json").read_text(encoding="utf-8"))
    spine_vertices = set(spines["spines"]["K_J0"]["vertices"])
    recorded = {tuple(coords) for coords in spines["spines"]["K_J0"]["vertex_coordinates"]}
    derived = {coords for coords in recorded if sum(1 for c in coords if c % PERIOD) <= 1}
    tetrahedra = triangulation["T"]["tetrahedra"]
    lifts = triangulation["T"]["integer_lifts"]["tetrahedra"]
    weights = [Fraction(4, 10), Fraction(3, 10), Fraction(2, 10), Fraction(1, 10)]
    checked = 0
    mismatches = 0
    for indices, corners in zip(tetrahedra, lifts):
        points = [tuple(F(c) for c in corner) for corner in corners]
        for order in itertools.permutations(range(4)):
            chain = []
            for size in range(1, 5):
                group = [points[order[j]] for j in range(size)]
                chain.append(tuple(sum(g[i] for g in group) / size for i in range(3)))
            probe = tuple(sum(weights[j] * chain[j][i] for j in range(4)) for i in range(3))
            if point_in_H0(probe) != (indices[order[0]] in spine_vertices):
                mismatches += 1
            checked += 1
    return {
        "tprime_tetrahedra_probed": checked,
        "mismatches": mismatches,
        "spine_vertex_rule_matches_commit3": derived == recorded,
        "spine_vertex_count": len(recorded),
    }


# ---------------------------------------------------------------------------
# the composition
# ---------------------------------------------------------------------------


def load_generators() -> list[Generator]:
    paths = sorted(GENERATOR_DIR.glob("gen_[0-9][0-9][0-9].json"))
    if len(paths) != 93:
        raise AssertionError(f"expected 93 generator files, found {len(paths)}")
    generators = [Generator(json.loads(path.read_text(encoding="utf-8"))) for path in paths]
    for position, generator in enumerate(generators):
        if generator.index != position:
            raise AssertionError("generator files are not in index order")
    return generators


def base_curves():
    curves = {}
    for axis in range(3):
        end = [Fraction(0), Fraction(0), Fraction(0)]
        end[axis] = Fraction(1)
        curves[f"C_{axis}"] = [(Fraction(0), Fraction(0), Fraction(0)), tuple(end)]
    for axis in range(3):
        start = [Fraction(0), Fraction(0), Fraction(0)]
        start[(axis + 1) % 3] = FRAMING_EPSILON
        end = list(start)
        end[axis] = Fraction(1)
        curves[f"C_{axis}_plus"] = [tuple(start), tuple(end)]
    return curves


def encode_polyline(points):
    return [[str(c) for c in p] for p in points]


def homology_class(points):
    shift = sub(points[-1], points[0])
    if any(c.denominator != 1 for c in shift):
        raise AssertionError("polyline is not a closed loop in the torus")
    return [int(c) for c in shift]


SPINE_NAMES = [f"C_{axis}" for axis in range(3)]
FRAMING_NAMES = [f"C_{axis}_plus" for axis in range(3)]


def local_normal_form(generators) -> dict[str, Any]:
    """``psi_A = A`` on ``B(0, 1/196104)``: an explicit operator-norm certificate."""
    prefix = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    norms = []
    for generator in generators:
        prefix = matmul(generator.integer_matrix, prefix)
        norms.append(infinity_norm(prefix))
    worst = max(norms)
    bound = PROTECTED_RADIUS * worst
    return {
        "claim": "psi_A(x) = A x for every x with sup-norm at most 1/196104",
        "argument": (
            "The support of every push Pi_k is at sup-norm distance 1/8 from Z^3, so a "
            "point of sup-norm below 1/8 is never pushed.  By induction the orbit of x "
            "after k generators is C_k x with C_k = E_{k-1} ... E_0, and "
            "max_k |C_k|_inf * 1/196104 < 1/8, so no push ever fires."
        ),
        "max_prefix_infinity_norm": worst,
        "orbit_bound": str(bound),
        "support_clearance": str(SUPPORT_LATTICE_CLEARANCE),
        "certificate_holds": bound < SUPPORT_LATTICE_CLEARANCE,
    }


def protected_ball_report(generators) -> dict[str, Any]:
    half = PROTECTED_RADIUS / 2
    generator = generators[0]
    column = next(
        j
        for j in range(3)
        if any(generator.integer_matrix[i][j] != (1 if i == j else 0) for i in range(3))
    )
    probe = [Fraction(0), Fraction(0), Fraction(0)]
    probe[column] = half
    linear_image = matvec(generator.matrix, tuple(probe))
    composite_image = matvec([[F(v) for v in row] for row in MATRIX_A], tuple(probe))
    return {
        "radius": str(PROTECTED_RADIUS),
        "push_factors_fix_the_ball_pointwise": True,
        "push_support_sup_norm_distance_to_lattice": str(SUPPORT_LATTICE_CLEARANCE),
        "linear_factors_fix_the_ball_pointwise": False,
        "linear_factor_witness": {
            "generator": generator.index,
            "point": [str(c) for c in probe],
            "sup_norm": str(half),
            "image": [str(c) for c in linear_image],
            "moved": tuple(linear_image) != tuple(probe),
        },
        "psi_A_fixes_the_ball_pointwise": False,
        "psi_A_witness": {
            "point": [str(c) for c in probe],
            "sup_norm": str(half),
            "image": [str(c) for c in composite_image],
            "moved": tuple(composite_image) != tuple(probe),
        },
        "note": (
            "Only the 93 push factors Pi_k fix the protected ball pointwise.  The 93 "
            "linear factors E_k are transvections and do not, so psi_A is the linear "
            "map A on that ball: it fixes 0 and moves everything else there.  A "
            "representative of the Johnson mapping class that is the identity near a "
            "point exists abstractly, but it is not psi_A = Pi_92 E_92 ... Pi_0 E_0."
        ),
    }


def setwise_preservation_report(generators) -> dict[str, Any]:
    generator = generators[0]
    target = None
    for j in range(3):
        column = [generator.integer_matrix[i][j] for i in range(3)]
        if column != [1 if i == j else 0 for i in range(3)]:
            target = j
    probe = [Fraction(0), Fraction(0), Fraction(0)]
    probe[target] = Fraction(1, 4)
    probe = tuple(probe)
    image = generator.apply_point(probe)
    return {
        "claim": "psi_k(H_J^0) = H_J^0 cannot hold for this relative representative",
        "reason": (
            "Set-wise preservation of the dual-block handlebody needs a slide map that "
            "hugs the boundary of the regular neighbourhood of the prefix axis: the "
            "sliding arc has to stay inside the tube around the e_p circle.  The Johnson "
            "relative representative used here bends the diagonal at the quarter points "
            "P = (1/4,1/4) and Q = (3/4,3/4) of the unit square and through m' at "
            "distance 1/4 from both axes.  Scaled to the period-4 mesh those are integer "
            "vertices with two non-zero coordinates; they are not vertices of the spine "
            "K_J^0, their hat-function maximum is attained off the spine, so they lie "
            "outside |H_J^0|.  Pulling the push in towards the axes would repair the "
            "handlebody condition but would drag the support into the protected ball and "
            "destroy the relative property, so one representative does not satisfy both."
        ),
        "witness": {
            "generator": generator.index,
            "point_of_K1": [str(c) for c in probe],
            "point_in_H_J0": point_in_H0(tuple(c * PERIOD for c in probe)),
            "image": [str(c) for c in image],
            "image_in_H_J0": point_in_H0(tuple(c * PERIOD for c in image)),
        },
        "status": "OPEN",
    }


def per_generator_diagnostics(generators) -> list[dict[str, Any]]:
    curves = base_curves()
    out = []
    for generator in generators:
        images = [generator.apply(curves[name]) for name in SPINE_NAMES]
        out.append(
            {
                "index": generator.index,
                "spine_image_vertex_counts": [len(p) for p in images],
                "spine_image_in_H_J0": all(polyline_in_H0(scale_to_period4(p)) for p in images),
                "max_sup_norm_distance_to_K1": str(
                    max(polyline_max_distance(p) for p in images)
                ),
                "bent_path": encode_polyline(images[
                    next(
                        j
                        for j in range(3)
                        if [generator.integer_matrix[i][j] for i in range(3)]
                        != [1 if i == j else 0 for i in range(3)]
                    )
                ]),
            }
        )
    return out


def prefix_transport(generators, budget: int, progress: bool) -> dict[str, Any]:
    curves = base_curves()
    reports = [
        {
            "steps": 0,
            "spine_vertex_counts": [len(curves[name]) for name in SPINE_NAMES],
            "framing_vertex_counts": [len(curves[name]) for name in FRAMING_NAMES],
            "spine_image_in_H_J0": all(
                polyline_in_H0(scale_to_period4(curves[name])) for name in SPINE_NAMES
            ),
            "max_curve_distance_to_K1": str(
                max(polyline_max_distance(curves[name]) for name in SPINE_NAMES)
            ),
        }
    ]
    first_exit = None
    completed = 0
    for step, generator in enumerate(generators, start=1):
        for name in list(curves):
            curves[name] = generator.apply(curves[name])
        completed = step
        polylines = [curves[name] for name in SPINE_NAMES]
        inside = all(polyline_in_H0(scale_to_period4(p)) for p in polylines)
        if not inside and first_exit is None:
            first_exit = step
        reports.append(
            {
                "steps": step,
                "spine_vertex_counts": [len(p) for p in polylines],
                "framing_vertex_counts": [len(curves[name]) for name in FRAMING_NAMES],
                "spine_image_in_H_J0": inside,
                "max_curve_distance_to_K1": str(
                    max(polyline_max_distance(p) for p in polylines)
                ),
            }
        )
        if progress:
            print(f"  prefix {step:3d} {reports[-1]['spine_vertex_counts']}", flush=True)
        if max(len(curve) for curve in curves.values()) > budget:
            break
    payload = {
        name: encode_polyline(curve) for name, curve in sorted(curves.items())
    }
    counts = [max(item["spine_vertex_counts"]) for item in reports]
    ratios = [
        str(Fraction(counts[i + 1], counts[i])) for i in range(len(counts) - 1) if counts[i]
    ]
    return {
        "vertex_budget": budget,
        "prefixes_completed": completed,
        "prefixes_requested": len(generators),
        "complete": completed == len(generators),
        "reports": reports,
        "first_prefix_leaving_H_J0": first_exit,
        "max_spine_vertex_counts": counts,
        "growth_ratios": ratios,
        "polygon_sha256": canonical_sha(payload),
        "final_homology_classes": {
            name: homology_class(curve) for name, curve in sorted(curves.items())
        },
        "status": (
            "COMPLETE"
            if completed == len(generators)
            else "OPEN: the exact polygon transport was stopped by the vertex budget; "
            "the number of linearity domains of the composite grows multiplicatively "
            "(measured factor about 1.25 per generator), so the exact 93-fold image "
            "polygon has of order 10^9 vertices and is not computed here"
        ),
    }


def point_sample_transport(generators, count: int) -> dict[str, Any]:
    """Exact images of a finite point sample under the full 93-fold composite."""
    samples: dict[str, list] = {}
    for axis in range(3):
        for name, offset in (
            (f"C_{axis}", Fraction(0)),
            (f"C_{axis}_plus", FRAMING_EPSILON),
        ):
            points = []
            for j in range(count):
                p = [Fraction(0), Fraction(0), Fraction(0)]
                p[axis] = Fraction(j, count)
                p[(axis + 1) % 3] = offset
                points.append(tuple(p))
            samples[name] = points
    images = {}
    for name, points in samples.items():
        current = points
        for generator in generators:
            current = [generator.apply_point(p) for p in current]
        images[name] = current
    payload = {name: encode_polyline(points) for name, points in sorted(images.items())}
    digits = max(
        len(str(c.denominator)) for points in images.values() for p in points for c in p
    )
    origin = images["C_0"][0]
    return {
        "sample_count_per_curve": count,
        "sample_rule": "the points j/count on each loop, j = 0 .. count-1",
        "image_sha256": canonical_sha(payload),
        "max_denominator_decimal_digits": digits,
        "image_of_the_origin": [str(c) for c in origin],
        "origin_is_fixed": tuple(origin) == (Fraction(0), Fraction(0), Fraction(0)),
        "first_images": {
            name: [[str(c) for c in p] for p in points[:2]]
            for name, points in sorted(images.items())
        },
        "note": (
            "This is an exact point sample of psi_A, not the image polygon: the "
            "polygon between two sampled points is not a straight segment."
        ),
    }


THETA_PATH = GENERATOR_DIR / "gen_093_section_straightening.json"


def section_straightening_report(generators) -> dict[str, Any]:
    """``Psi = psi_A o theta`` is the identity on the cube of radius ``r_inner``.

    ``theta`` is the linear map ``A^{-1}`` on ``C_in`` (its innermost cone cells
    all carry that one matrix), and ``A^{-1} C_in`` lies well inside the cube on
    which ``psi_A`` is exactly ``A``.  So ``Psi(x) = A A^{-1} x = x`` there.  The
    check below is not only that argument: a sample of points of ``C_in``
    (including its corners) is pushed through ``A^{-1}`` and then through all 93
    generators one point at a time, and compared with the starting point.
    """
    if not THETA_PATH.exists():
        return {"status": "MISSING", "file": str(THETA_PATH.relative_to(ROOT))}
    theta = json.loads(THETA_PATH.read_text(encoding="utf-8"))
    inverse_a = [[F(v) for v in row] for row in theta["matrix_A_inverse"]]
    matrix_a = [[F(v) for v in row] for row in MATRIX_A]
    r_inner = F(theta["r_inner"])
    r_outer = F(theta["r_outer"])
    norm = max(sum(abs(entry) for entry in row) for row in inverse_a)
    if norm.denominator != 1:
        raise AssertionError("A^{-1} is not integral")
    norm = int(norm)

    linear = local_normal_form(generators)
    inside_regime = norm * r_inner < r_outer and r_outer <= PROTECTED_RADIUS

    probes = [(Fraction(0), Fraction(0), Fraction(0))]
    for sx in (1, -1):
        for sy in (1, -1):
            for sz in (1, -1):
                probes.append((sx * r_inner, sy * r_inner, sz * r_inner))
    for j in (1, 2, 3, 5, 7):
        probes.append(
            (r_inner * Fraction(j, 8), -r_inner * Fraction(j, 11), r_inner * Fraction(j, 13))
        )
    failures = []
    for probe in probes:
        moved = matvec(inverse_a, probe)
        if max(abs(c) for c in moved) >= r_outer:
            failures.append("theta image leaves the linear regime")
            continue
        current = moved
        for generator in generators:
            current = generator.apply_point(current)
        if tuple(current) != tuple(probe):
            failures.append(f"Psi moved {[str(c) for c in probe]} to {[str(c) for c in current]}")
    return {
        "file": str(THETA_PATH.relative_to(ROOT)),
        "theta_sha256": theta["sha256"],
        "r_outer": str(r_outer),
        "r_inner": str(r_inner),
        "matrix_A_inverse_infinity_norm": norm,
        "theta_image_of_C_in_sup_radius_bound": str(norm * r_inner),
        "inside_linear_regime_of_psi_A": inside_regime,
        "linear_regime_certificate": linear["certificate_holds"],
        "probe_count": len(probes),
        "probes_returned_to_themselves": not failures,
        "failures": failures,
        "induced_H1_matrix_of_Psi": MATRIX_A,
        "induced_H1_note": (
            "theta is supported in a ball, hence isotopic to the identity and trivial on "
            "H_1, so Psi = psi_A o theta induces the same matrix A as psi_A."
        ),
        "matrix_A_times_its_inverse_is_identity": matmul(
            [[int(v) for v in row] for row in MATRIX_A],
            [[int(entry) for entry in row] for row in inverse_a],
        )
        == [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "fixed_ball_radius": str(r_inner),
        "status": "PASS" if (not failures and inside_regime) else "FAIL",
    }


def run(budget: int = DEFAULT_VERTEX_BUDGET, samples: int = DEFAULT_SAMPLE_COUNT,
        progress: bool = False, limit: int | None = None) -> dict[str, Any]:
    generators = load_generators()
    if limit is not None:
        generators = generators[:limit]

    composite = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    for generator in generators:
        composite = matmul(generator.integer_matrix, composite)

    per_generator = per_generator_diagnostics(generators)
    transport = prefix_transport(generators, budget, progress)
    sample = point_sample_transport(generators, samples)

    document: dict[str, Any] = {
        "schema": "t73_psi_A_composite/v1",
        "generator": "scripts/compose_t73_psi_A.py",
        "generator_source": "geometry/t73_johnson_generators/gen_000.json ... gen_092.json",
        "generator_count": len(generators),
        "composition_order": "psi_A = psi_92 o ... o psi_0 (psi_0 applied to points first)",
        "composite_linear_matrix": composite,
        "matrix_A": MATRIX_A,
        "composite_matrix_equals_A": composite == MATRIX_A,
        "induced_H1_matrix": composite,
        "spine_image_homology_classes": {
            f"C_{axis}": [composite[row][axis] for row in range(3)] for axis in range(3)
        },
        "framing": {
            "epsilon": str(FRAMING_EPSILON),
            "rule": "C_i^+ = C_i + epsilon * e_{(i+1) mod 3} (Aitchison-Rubinstein product framing)",
            "homology_classes": {
                f"C_{axis}_plus": [composite[row][axis] for row in range(3)] for axis in range(3)
            },
        },
        "local_normal_form": local_normal_form(generators),
        "protected_ball": protected_ball_report(generators),
        "section_straightening": section_straightening_report(generators),
        "exact_prefix_transport": transport,
        "point_sample_transport": sample,
        "handlebody_diagnostics": {
            "reference": "geometry/t73_handlebody_pair_dual_block.json (H_J0, period-4 mesh)",
            "period_conversion": "period-1 points are multiplied by 4",
            "test": (
                "membership is tested against the CLOSED subcomplex |H_J^0| (a stronger "
                "requirement to fail than the interior).  A segment is inside iff every "
                "point is: the segment is cut at every wall of the piecewise-linear "
                "structure (the integer planes and the diagonal planes x_i - x_j in Z of "
                "the Freudenthal mesh, then the crossings of the four barycentric "
                "coordinates), and on each resulting open piece the set of vertices "
                "attaining the maximal hat value is constant, so one interior probe per "
                "piece decides it exactly.  The probe is cross-checked against COMMIT 3 on "
                "an interior point of each of the 9216 T'-tetrahedra (--crosscheck)."
            ),
            "per_generator": per_generator,
            "per_generator_pass_count": sum(
                1 for item in per_generator if item["spine_image_in_H_J0"]
            ),
            "first_prefix_leaving_H_J0": transport["first_prefix_leaving_H_J0"],
            "composite_spine_image_in_H_J0": False
            if transport["first_prefix_leaving_H_J0"] is not None
            else None,
            "setwise_preservation": setwise_preservation_report(generators),
        },
        "attaching_link_status": (
            "OPEN: without exact set-wise preservation of the Heegaard pair the "
            "Aitchison-Rubinstein attaching curves psi_A(C_i^+) on the splitting surface "
            "are not defined.  No attaching link is produced by this script."
        ),
    }
    document["psi_A_sha256"] = canonical_sha(document)
    return document


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--budget", type=int, default=DEFAULT_VERTEX_BUDGET)
    parser.add_argument("--samples", type=int, default=DEFAULT_SAMPLE_COUNT)
    parser.add_argument("--limit", type=int)
    parser.add_argument("--progress", action="store_true")
    parser.add_argument("--crosscheck", action="store_true")
    args = parser.parse_args()

    ok = True
    if args.crosscheck:
        report = crosscheck_membership()
        print(json.dumps(report, indent=2, sort_keys=True))
        print(f"H_J0_MEMBERSHIP_CROSSCHECK={'PASS' if report['mismatches'] == 0 else 'FAIL'}")
        ok = ok and report["mismatches"] == 0

    document = run(
        budget=args.budget, samples=args.samples, progress=args.progress, limit=args.limit
    )
    ok = ok and document["composite_matrix_equals_A"]
    ok = ok and document["local_normal_form"]["certificate_holds"]

    if args.write and args.limit is None:
        OUTPUT.write_text(
            json.dumps(document, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8"
        )
        print(f"WROTE={OUTPUT.relative_to(ROOT)} BYTES={OUTPUT.stat().st_size}")
    if args.check:
        if not OUTPUT.exists():
            print("COMMITTED_PSI_A=FAIL MISSING")
            ok = False
        else:
            same = json.loads(OUTPUT.read_text(encoding="utf-8")) == document
            print(f"COMMITTED_PSI_A={'PASS' if same else 'FAIL'}")
            ok = ok and same

    diagnostics = document["handlebody_diagnostics"]
    transport = document["exact_prefix_transport"]
    print(f"JOHNSON_GENERATORS={document['generator_count']}")
    print(f"INDUCED_MATRIX_EQUALS_A={'PASS' if document['composite_matrix_equals_A'] else 'FAIL'}")
    print(
        "PROTECTED_BALL_FIXED="
        f"{'PASS' if document['protected_ball']['psi_A_fixes_the_ball_pointwise'] else 'FAIL'}"
    )
    print("PROTECTED_BALL_FIXED_BY_PUSH_FACTORS=PASS")
    print(
        "PSI_A_ON_PROTECTED_BALL=LINEAR_A "
        f"certificate={'PASS' if document['local_normal_form']['certificate_holds'] else 'FAIL'}"
    )
    section = document["section_straightening"]
    print(
        f"PSI_FIXES_SECTION_BALL={section['status']} radius={section.get('fixed_ball_radius')}"
    )
    print(
        "SPINE_IMAGE_IN_H0_PER_GENERATOR="
        f"{diagnostics['per_generator_pass_count']}/{document['generator_count']}"
    )
    print(
        "COMPOSITE_SPINE_IMAGE_IN_H0=FAIL "
        f"first_exit_step={diagnostics['first_prefix_leaving_H_J0']}"
    )
    print("HEEGAARD_PAIR_EXACT_PRESERVATION=OPEN")
    print(
        "EXACT_COMPOSITE_POLYGON="
        f"{'COMPLETE' if transport['complete'] else 'OPEN'} "
        f"prefixes_completed={transport['prefixes_completed']}/{transport['prefixes_requested']} "
        f"max_vertices={max(transport['max_spine_vertex_counts'])}"
    )
    print(f"PREFIX_POLYGON_SHA256={transport['polygon_sha256']}")
    print(f"POINT_SAMPLE_SHA256={document['point_sample_transport']['image_sha256']}")
    print(f"PSI_A_SHA256={document['psi_A_sha256']}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
